<?php
    $_CONFIG = [
        'app' => [
            'web_title' => 'Expedite',
            'public_key' => 'expedite',
            'private_key' => 'expedite',
            'base_url' => [
                'local' => 'http://127.0.0.1/expedite/',
                'production' => 'https://expediteph.com/'
            ],
            'email' => [
                'host' => 'smtp.hostinger.com',
                'port' => 465,
                'smtp_secure' => 'ssl',
                'smtp_auth' => true,
                'username' => 'noreply@expediteph.com',
                'password' => 'expeditePH@2022',
                'from' => 'noreply@expediteph.com',
                'fromName' => 'Expedite PH'
            ],
            'twitter' => 'https://twitter.com/ExpeditePH',
            'facebook' => 'https://www.facebook.com/expeditephilippines',
            'instagram' => 'https://www.instagram.com/expediteph',
            'partner' => [
                'skills' => [
                    'Accounting and Bookkeeping' => array(
                        'Financial statements',
                        'Tax preparation',
                        'Budgeting',
                        'Payroll processing',
                        'Accounts payable',
                        'Accounts receivable',
                        'Financial reporting',
                        'Audit assistance',
                        'Bookkeeping software',
                        'Inventory management',
                        'Cost analysis',
                        'Cash flow management',
                        'Financial forecasting',
                        'Bank reconciliation',
                        'Expense tracking',
                        'Financial analysis',
                        'Income statements',
                        'Balance sheets',
                        'General ledger',
                        'Accounting software',
                    ),
                    'Financial Planning' => array(
                        'Investment management',
                        'Retirement planning',
                        'Wealth management',
                        'Risk assessment',
                        'Estate planning',
                        'Tax planning',
                        'Insurance planning',
                        'College savings planning',
                        'Debt management',
                        'Cash flow analysis',
                        'Financial goal setting',
                        'Asset allocation',
                        'Portfolio analysis',
                        'Financial modeling',
                        'Savings strategies',
                        'Financial projections',
                        'Financial education',
                        'Tax optimization',
                        'Financial advising',
                        'Financial planning software',
                    ),
                    'Recruiting and Human Resources' => array(
                        'Talent acquisition',
                        'Job posting',
                        'Resume screening',
                        'Interviewing',
                        'Employee onboarding',
                        'Compensation management',
                        'Performance evaluation',
                        'Employee benefits administration',
                        'HR policies and procedures',
                        'Employee relations',
                        'Workforce planning',
                        'Succession planning',
                        'Employee engagement',
                        'Organizational development',
                        'Labor law compliance',
                        'HR analytics',
                        'HR software',
                        'Employment branding',
                        'Employee training and development',
                        'Diversity and inclusion',
                    ),
                    'Management Consulting and Analysis' => array(
                        'Business strategy',
                        'Process improvement',
                        'Change management',
                        'Organizational design',
                        'Performance measurement',
                        'Risk management',
                        'Operations analysis',
                        'Benchmarking',
                        'Market research',
                        'Competitive analysis',
                        'Financial analysis',
                        'Data-driven decision making',
                        'Strategic planning',
                        'Project management',
                        'Leadership development',
                        'Team building',
                        'Management training',
                        'Business intelligence',
                        'Management consulting software',
                        'Management consulting frameworks',
                    ),
                    'Personal and Professional Coaching' => array(
                        'Life coaching',
                        'Career coaching',
                        'Executive coaching',
                        'Leadership coaching',
                        'Goal setting',
                        'Motivational coaching',
                        'Time management',
                        'Stress management',
                        'Communication skills',
                        'Confidence building',
                        'Work-life balance',
                        'Self-awareness',
                        'Emotional intelligence',
                        'Mindfulness coaching',
                        'Performance coaching',
                        'Career transition coaching',
                        'Relationship coaching',
                        'Personal development',
                        'Positive psychology',
                        'Coaching methodologies',
                    ),
                    'Data Entry and Transcription' => array(
                        'Data typing',
                        'Data processing',
                        'Data verification',
                        'Data cleansing',
                        'Data organization',
                        'Data indexing',
                        'Data formatting',
                        'Transcription services',
                        'Audio-to-text conversion',
                        'Video-to-text conversion',
                        'Data entry accuracy',
                        'Data entry software',
                        'Data entry automation',
                        'Data entry quality control',
                        'Proofreading',
                        'Data confidentiality',
                        'Data security',
                        'Data entry tools',
                        'Data entry efficiency',
                        'Data entry speed',
                    ),
                    'Virtual Assistant' => array(
                        'Administrative support',
                        'Email management',
                        'Calendar management',
                        'Appointment scheduling',
                        'Travel arrangements',
                        'File organization',
                        'Document editing',
                        'Internet research',
                        'Social media management',
                        'Data entry',
                        'Customer support',
                        'Event coordination',
                        'Online shopping assistance',
                        'Personal errands',
                        'Content creation',
                        'Project coordination',
                        'Meeting minutes',
                        'Task management',
                        'Virtual meeting facilitation',
                        'Virtual assistant software',
                    ),
                    'Market Research and Product' => array(
                        'Competitor analysis',
                        'Consumer behavior',
                        'Market segmentation',
                        'Survey design',
                        'Data collection',
                        'Data analysis',
                        'Market trends',
                        'Product development',
                        'Brand positioning',
                        'Customer insights',
                        'Market forecasting',
                        'Market sizing',
                        'Marketing strategy',
                        'Product pricing',
                        'Product testing',
                        'Focus groups',
                        'Market research reports',
                        'Market research software',
                        'Market research methodologies',
                        'Marketing analytics',
                    ),
                    'Project Management' => array(
                        'Project planning',
                        'Task scheduling',
                        'Resource allocation',
                        'Risk management',
                        'Budget management',
                        'Project tracking',
                        'Project coordination',
                        'Stakeholder management',
                        'Team collaboration',
                        'Project documentation',
                        'Project communication',
                        'Milestone tracking',
                        'Project evaluation',
                        'Agile project management',
                        'Scrum methodology',
                        'Kanban methodology',
                        'Project management software',
                        'Project management frameworks',
                        'Project management tools',
                        'Project management certifications',
                    ),
                    'Community Management and Tagging' => array(
                        'Social media management',
                        'Online community building',
                        'Content moderation',
                        'Community engagement',
                        'User support',
                        'Forum management',
                        'Brand advocacy',
                        'Community guidelines',
                        'User-generated content',
                        'Community analytics',
                        'Tagging and categorization',
                        'Content tagging',
                        'Content classification',
                        'Content organization',
                        'Content discovery',
                        'Content recommendation',
                        'User profiling',
                        'Community platform management',
                        'Community management software',
                        'Community management strategies',
                    ),
                    'Customer Service and Technology' => array(
                        'Customer support',
                        'Help desk management',
                        'Ticketing systems',
                        'Live chat support',
                        'Email support',
                        'Phone support',
                        'Knowledge base management',
                        'Self-service support',
                        'Customer satisfaction',
                        'Customer feedback',
                        'Customer retention',
                        'Technical support',
                        'Troubleshooting',
                        'Product training',
                        'Service level agreements',
                        'Customer relationship management',
                        'Customer experience management',
                        'Omni-channel support',
                        'Customer service software',
                        'Customer service metrics',
                    ),
                    'AI and Machine Learning' => array(
                        'Machine learning algorithms',
                        'Deep learning',
                        'Natural language processing',
                        'Computer vision',
                        'Predictive modeling',
                        'Pattern recognition',
                        'Data preprocessing',
                        'Feature engineering',
                        'Model training',
                        'Model evaluation',
                        'Model deployment',
                        'Anomaly detection',
                        'Recommendation systems',
                        'Speech recognition',
                        'Image recognition',
                        'Text classification',
                        'Data labeling',
                        'Model optimization',
                        'AI ethics',
                        'AI frameworks',
                    ),
                    'Data Analysis and Testing' => array(
                        'Statistical analysis',
                        'Hypothesis testing',
                        'Data visualization',
                        'Data exploration',
                        'Descriptive statistics',
                        'Correlation analysis',
                        'Regression analysis',
                        'Time series analysis',
                        'Data cleaning',
                        'Data modeling',
                        'Data validation',
                        'Data quality assurance',
                        'Data interpretation',
                        'Data-driven decision making',
                        'A/B testing',
                        'Experimental design',
                        'Data analysis software',
                        'Data analysis techniques',
                        'Data analysis tools',
                        'Data analysis frameworks',
                    ),
                    'Data Design and Visualization' => array(
                        'Information design',
                        'Visual storytelling',
                        'Data mapping',
                        'Infographics',
                        'Data dashboards',
                        'Data presentation',
                        'Data storytelling',
                        'Data visualization techniques',
                        'Data visualization tools',
                        'Data visualization software',
                        'Interactive visualizations',
                        'Data-driven design',
                        'Data visualization best practices',
                        'Data visualization frameworks',
                        'Data visualization libraries',
                        'Data visualization trends',
                        'Data visualization case studies',
                        'User-centered data design',
                        'Data design principles',
                        'Data design aesthetics',
                    ),
                    'Data Extraction/ETL' => array(
                        'Data extraction',
                        'Data transformation',
                        'Data loading',
                        'ETL',
                        'Data integration',
                        'Data migration',
                        'Data warehousing',
                        'Data cleansing',
                        'Data synchronization',
                        'Data extraction tools',
                        'Data extraction techniques',
                        'ETL tools',
                        'Data pipeline',
                        'Data ingestion',
                        'Data connectors',
                        'Data extraction frameworks',
                        'Data extraction best practices',
                        'Data extraction methodologies',
                        'Data extraction automation',
                        'Data extraction scalability',
                    ),
                    'Data Mining and Management' => array(
                        'Data exploration',
                        'Data preprocessing',
                        'Data integration',
                        'Data warehousing',
                        'Data clustering',
                        'Data classification',
                        'Data association',
                        'Text mining',
                        'Web mining',
                        'Social media mining',
                        'Pattern recognition',
                        'Data governance',
                        'Data privacy',
                        'Data security',
                        'Data storage',
                        'Data indexing',
                        'Data retrieval',
                        'Data management tools',
                        'Data mining algorithms',
                        'Data mining software',
                    ),
                    'Arts and Illustration' => array(
                        'Traditional art',
                        'Digital art',
                        'Illustration',
                        'Painting',
                        'Drawing',
                        'Sketching',
                        'Watercolor',
                        'Oil painting',
                        'Graphic design',
                        'Character design',
                        'Concept art',
                        'Storyboarding',
                        'Comic art',
                        'Cartooning',
                        'Typography',
                        'Printmaking',
                        'Mixed media',
                        'Collage',
                        'Sculpture',
                        'Artistic techniques',
                    ),
                    'Audio and Music Production' => array(
                        'Music composition',
                        'Audio editing',
                        'Sound design',
                        'Recording',
                        'Mixing',
                        'Mastering',
                        'Music production software',
                        'Virtual instruments',
                        'Synthesis',
                        'Sampling',
                        'Beatmaking',
                        'Arrangement',
                        'Music theory',
                        'MIDI programming',
                        'Audio effects',
                        'Foley',
                        'Field recording',
                        'Voiceover',
                        'Podcast production',
                        'Audio production techniques',
                    ),
                    'Branding and Logo Design' => array(
                        'Brand identity',
                        'Logo design',
                        'Brand strategy',
                        'Brand positioning',
                        'Brand guidelines',
                        'Visual identity',
                        'Typography',
                        'Color theory',
                        'Brand messaging',
                        'Brand storytelling',
                        'Brand recognition',
                        'Brand reputation',
                        'Logo concept development',
                        'Logo typography',
                        'Logo symbolism',
                        'Logo color psychology',
                        'Logo design principles',
                        'Logo design trends',
                        'Brand design best practices',
                        'Logo design software',
                    ),
                    'Graphic, Editorial and Presentation Design' => array(
                        'Graphic design',
                        'Editorial design',
                        'Publication design',
                        'Layout design',
                        'Typography',
                        'Infographic design',
                        'Poster design',
                        'Brochure design',
                        'Magazine design',
                        'Book design',
                        'Print design',
                        'Packaging design',
                        'Corporate branding design',
                        'Visual storytelling',
                        'Presentation design',
                        'Slide design',
                        'Presentation templates',
                        'Information design',
                        'Visual hierarchy',
                        'Color theory in design',
                    ),
                    'NFT, AR/VR and Game Art' => array(
                        'NFT (Non-fungible token)',
                        'Digital art',
                        'Crypto art',
                        'Blockchain technology',
                        'AR (Augmented reality)',
                        'VR (Virtual reality)',
                        'Game art',
                        'Character design',
                        'Environment design',
                        '3D modeling',
                        'Texture mapping',
                        'Animation',
                        'Rigging',
                        'Game design',
                        'Game development',
                        'Game engines',
                        'Interactive experiences',
                        'Real-time rendering',
                        'Pixel art',
                        'Concept art for games',
                    ),
                    'Performing Arts' => array(
                        'Theater',
                        'Dance',
                        'Music',
                        'Acting',
                        'Singing',
                        'Modeling',
                        'Musical theater',
                        'Improvisation',
                        'Stage presence',
                        'Physical theater',
                        'Performance art',
                        'Playwriting',
                        'Script analysis',
                        'Theatrical lighting',
                        'Stage management',
                        'Choreography',
                        'Theater production',
                        'Vocal techniques',
                        'Character development',
                        'Theatrical costumes',
                        'Theater history and theory',
                    ),
                    'Photography' => array(
                        'Portrait photography',
                        'Landscape photography',
                        'Street photography',
                        'Fashion photography',
                        'Product photography',
                        'Event photography',
                        'Wedding photography',
                        'Fine art photography',
                        'Photo editing',
                        'Composition',
                        'Lighting techniques',
                        'Exposure',
                        'Color grading',
                        'Photo retouching',
                        'Digital photography',
                        'Analog photography',
                        'Camera equipment',
                        'Photography genres',
                        'Photography software',
                        'Photography tips and tricks',
                    ),
                    'Product Design' => array(
                        'Product ideation',
                        'User research',
                        'User experience (UX) design',
                        'User interface (UI) design',
                        'Wireframing',
                        'Prototyping',
                        'Interaction design',
                        'Product testing',
                        'Iterative design',
                        'Design thinking',
                        'Industrial design',
                        'Product aesthetics',
                        'Material selection',
                        'Ergonomics',
                        'Packaging design',
                        'Product usability',
                        'Design validation',
                        'Design documentation',
                        'Product design tools',
                        'Product design trends',
                    ),
                    'Video and Animation' => array(
                        'Video production',
                        'Motion graphics',
                        '2D animation',
                        '3D animation',
                        'Visual effects',
                        'Storyboarding',
                        'Character animation',
                        'Explainer videos',
                        'Animated logos',
                        'Whiteboard animation',
                        'Stop motion animation',
                        'Animated infographics',
                        'Typography animation',
                        'Video editing',
                        'Color grading',
                        'Cinematography',
                        'Sound design',
                        'Video post-production',
                        'Video marketing',
                        'Video optimization',
                    ),
                    '3D Modeling and CAD' => array(
                        '3D modeling',
                        'CAD (Computer-Aided Design)',
                        'Product design',
                        'Industrial design',
                        'Architectural visualization',
                        'Character modeling',
                        'Organic modeling',
                        'Hard surface modeling',
                        'Texturing',
                        'Lighting',
                        'Rendering',
                        '3D printing',
                        'CAD drafting',
                        'Parametric modeling',
                        'Mechanical engineering',
                        'Architectural design',
                        'Virtual reality modeling',
                        'Augmented reality modeling',
                        'CAD software',
                        '3D modeling techniques',
                    ),
                    'Building and Landscape Architecture' => array(
                        'Architectural design',
                        'Building plans',
                        'Construction drawings',
                        'Site planning',
                        'Urban design',
                        'Landscape design',
                        'Sustainable design',
                        'Green building',
                        'Interior design',
                        'Building materials',
                        'Structural engineering',
                        'Building codes and regulations',
                        'Building systems',
                        'Space planning',
                        'Building renovation',
                        'Building aesthetics',
                        'Building modeling',
                        'Building construction',
                        'Landscape planning',
                        'Landscape architecture software',
                    ),
                    'Chemical Engineering' => array(
                        'Chemical processes',
                        'Chemical reactions',
                        'Process design',
                        'Process optimization',
                        'Chemical plant design',
                        'Chemical equipment design',
                        'Chemical separations',
                        'Fluid dynamics',
                        'Heat transfer',
                        'Mass transfer',
                        'Reaction engineering',
                        'Process control',
                        'Chemical kinetics',
                        'Thermodynamics',
                        'Chemical modeling',
                        'Process simulation',
                        'Chemical safety',
                        'Chemical engineering software',
                        'Chemical engineering principles',
                        'Chemical engineering calculations',
                    ),
                    'Contract Manufacturing' => array(
                        'Manufacturing processes',
                        'Product assembly',
                        'Quality control',
                        'Supply chain management',
                        'Production planning',
                        'Material sourcing',
                        'Logistics',
                        'Packaging and labeling',
                        'Inventory management',
                        'Production efficiency',
                        'Outsourcing',
                        'Vendor management',
                        'Manufacturing standards',
                        'Manufacturing equipment',
                        'Lean manufacturing',
                        'Six Sigma',
                        'Continuous improvement',
                        'Cost optimization',
                        'Contract manufacturing services',
                        'Contract manufacturing agreements',
                    ),
                    'Electrical and Electronic Engineering' => array(
                        'Circuit design',
                        'Electronics prototyping',
                        'Printed circuit board (PCB) design',
                        'Analog electronics',
                        'Digital electronics',
                        'Power electronics',
                        'Microcontrollers',
                        'Signal processing',
                        'Control systems',
                        'Embedded systems',
                        'Wireless communication',
                        'Electrical wiring',
                        'Electrical safety',
                        'Electronic testing',
                        'Electronic troubleshooting',
                        'Electronic components',
                        'Power distribution',
                        'Power systems',
                        'Electromagnetic compatibility',
                        'Electrical engineering software',
                    ),
                    'Energy and Mechanical Engineering' => array(
                        'Energy systems',
                        'Renewable energy',
                        'Thermodynamics',
                        'Fluid mechanics',
                        'Heat transfer',
                        'Energy efficiency',
                        'Energy conservation',
                        'Power generation',
                        'HVAC',
                        'Mechanical design',
                        'Mechanical analysis',
                        'Mechanical simulations',
                        'Mechanical testing',
                        'Mechatronics',
                        'Robotics',
                        'Mechanical systems',
                        'Fluid dynamics',
                        'Energy storage',
                        'Energy management',
                        'Energy engineering software',
                    ),
                    'Interior and Trade Show Design' => array(
                        'Interior design',
                        'Space planning',
                        'Color schemes',
                        'Furniture selection',
                        'Lighting design',
                        'Material selection',
                        'Textile design',
                        'Room layouts',
                        'Interior styling',
                        'Environmental design',
                        'Trade show booth design',
                        'Exhibition design',
                        'Signage design',
                        'Floor plan design',
                        'Visual merchandising',
                        'Spatial branding',
                        'Experiential design',
                        '3D rendering',
                        'Interior design software',
                        'Trade show design trends',
                    ),
                    'Physical Sciences' => array(
                        'Physics',
                        'Chemistry',
                        'Biology',
                        'Geology',
                        'Astronomy',
                        'Mathematics',
                        'Environmental science',
                        'Materials science',
                        'Nanotechnology',
                        'Astrophysics',
                        'Quantum mechanics',
                        'Biophysics',
                        'Organic chemistry',
                        'Genetics',
                        'Ecology',
                        'Evolutionary biology',
                        'Statistical analysis',
                        'Thermodynamics',
                        'Scientific research',
                        'Laboratory techniques',
                    ),
                    'Database Management and Administration' => array(
                        'Database design',
                        'Database development',
                        'SQL',
                        'Database optimization',
                        'Data modeling',
                        'Data normalization',
                        'Data indexing',
                        'Data integrity',
                        'Database security',
                        'Data backup and recovery',
                        'Database performance tuning',
                        'Data migration',
                        'Database administration',
                        'Database monitoring',
                        'Database replication',
                        'Query optimization',
                        'Database scalability',
                        'Database architecture',
                        'Database management systems',
                        'Database administration tools',
                    ),
                    'DevOps and Solution Architecture' => array(
                        'DevOps methodologies',
                        'Continuous integration',
                        'Continuous deployment',
                        'Infrastructure as code',
                        'Configuration management',
                        'Deployment automation',
                        'Containerization',
                        'Orchestration',
                        'Microservices architecture',
                        'Scalable architecture',
                        'High availability',
                        'Fault tolerance',
                        'Monitoring and alerting',
                        'Performance optimization',
                        'System scalability',
                        'Cloud computing',
                        'Solution architecture design',
                        'DevOps tools',
                        'DevOps best practices',
                        'DevOps culture',
                    ),
                    'ERP/CRM Software' => array(
                        'Enterprise resource planning (ERP)',
                        'Customer relationship management (CRM)',
                        'ERP implementation',
                        'CRM implementation',
                        'ERP modules',
                        'CRM modules',
                        'Business process management',
                        'Data integration',
                        'Workflow automation',
                        'Data analysis and reporting',
                        'Sales management',
                        'Marketing automation',
                        'Customer support management',
                        'Inventory management',
                        'Order management',
                        'Supply chain management',
                        'ERP/CRM customization',
                        'ERP/CRM security',
                        'ERP/CRM integration',
                        'ERP/CRM software selection',
                    ),
                    'Information Security and Compliance' => array(
                        'Cybersecurity',
                        'Network security',
                        'Data privacy',
                        'Security risk assessment',
                        'Vulnerability management',
                        'Security incident response',
                        'Security policies and procedures',
                        'Access control',
                        'Identity and access management',
                        'Security auditing',
                        'Security awareness training',
                        'Compliance regulations',
                        'Data protection',
                        'Security governance',
                        'Security assessment',
                        'Penetration testing',
                        'Threat intelligence',
                        'Security monitoring',
                        'Security frameworks',
                        'Security best practices',
                    ),
                    'Network and System Administration' => array(
                        'Network configuration',
                        'Network monitoring',
                        'Network troubleshooting',
                        'Network security',
                        'Server administration',
                        'System performance optimization',
                        'Backup and recovery',
                        'Virtualization',
                        'Cloud computing',
                        'Firewall management',
                        'DNS management',
                        'Load balancing',
                        'IT infrastructure management',
                        'Patch management',
                        'Storage management',
                        'Network protocols',
                        'Remote access management',
                        'Disaster recovery planning',
                        'Network documentation',
                        'System administration tools',
                    ),
                    'Corporate and Contract Law' => array(
                        'Contract drafting',
                        'Contract negotiation',
                        'Contract review',
                        'Business agreements',
                        'Intellectual property law',
                        'Employment law',
                        'Corporate governance',
                        'Company formation',
                        'Mergers and acquisitions',
                        'Commercial law',
                        'Securities law',
                        'Compliance regulations',
                        'Contract disputes',
                        'Contract law interpretation',
                        'Legal research',
                        'Legal writing',
                        'Legal advice',
                        'Corporate litigation',
                        'Corporate law ethics',
                        'Legal contract templates',
                    ),
                    'Finance and Tax Law' => array(
                        'Financial planning',
                        'Tax planning',
                        'Tax compliance',
                        'Tax regulations',
                        'Tax preparation',
                        'Corporate finance',
                        'Investment law',
                        'Securities law',
                        'Banking law',
                        'Business finance',
                        'Accounting law',
                        'Auditing regulations',
                        'Financial reporting',
                        'Risk management',
                        'Financial transactions',
                        'Capital markets',
                        'Insurance law',
                        'Financial contracts',
                        'Tax litigation',
                        'Tax optimization',
                    ),
                    'International and Immigration Law' => array(
                        'International trade law',
                        'Cross-border transactions',
                        'Immigration law',
                        'Visa applications',
                        'Asylum and refugee law',
                        'International human rights law',
                        'International arbitration',
                        'International contracts',
                        'Customs and import/export law',
                        'International business law',
                        'Global compliance',
                        'International tax law',
                        'International investment law',
                        'Citizenship and nationality law',
                        'International dispute resolution',
                        'Extradition law',
                        'International labor law',
                        'International family law',
                        'International intellectual property law',
                        'International criminal law',
                    ),
                    'Public Law' => array(
                        'Constitutional law',
                        'Administrative law',
                        'Legislation and regulatory compliance',
                        'Government contracts',
                        'Public policy analysis',
                        'Public administration',
                        'Legislative drafting',
                        'Judicial review',
                        'Human rights law',
                        'Environmental law',
                        'Education law',
                        'Healthcare law',
                        'Social welfare law',
                        'Government transparency and accountability',
                        'Election law',
                        'Public interest litigation',
                        'Freedom of speech',
                        'Government ethics',
                        'Public law advocacy',
                        'Public law research',
                    ),
                    'Digital Marketing' => array(
                        'Search engine optimization (SEO)',
                        'Social media marketing',
                        'Pay-per-click (PPC) advertising',
                        'Content marketing',
                        'Email marketing',
                        'Influencer marketing',
                        'Online advertising',
                        'Marketing analytics',
                        'Digital strategy',
                        'Conversion rate optimization',
                        'Marketing automation',
                        'Social media management',
                        'Online reputation management',
                        'Web analytics',
                        'Digital advertising campaigns',
                        'Online lead generation',
                        'Customer relationship management (CRM)',
                        'A/B testing',
                        'Marketing funnels',
                        'Data-driven marketing',
                    ),
                    'Lead Generation and Telemarketing' => array(
                        'Lead generation strategy',
                        'Prospecting',
                        'Cold calling',
                        'Telemarketing campaigns',
                        'Database building',
                        'Lead nurturing',
                        'Appointment setting',
                        'Sales funnel management',
                        'Lead qualification',
                        'Customer profiling',
                        'Market research',
                        'Data enrichment',
                        'B2B lead generation',
                        'B2C lead generation',
                        'Lead scoring',
                        'Lead tracking',
                        'CRM integration',
                        'Telemarketing scripts',
                        'Lead generation tools',
                        'Lead generation analytics',
                    ),
                    'Marketing, PR and Brand Strategy' => array(
                        'Brand positioning',
                        'Brand identity development',
                        'Marketing strategy',
                        'Public relations',
                        'Media relations',
                        'Corporate communications',
                        'Brand storytelling',
                        'Content strategy',
                        'Event planning',
                        'Influencer strategy',
                        'Thought leadership',
                        'Reputation management',
                        'Crisis communications',
                        'Brand guidelines',
                        'Marketing campaigns',
                        'Brand awareness',
                        'Market research and analysis',
                        'Competitor analysis',
                        'Marketing metrics and analytics',
                        'Brand strategy consulting',
                    ),
                    'Language Tutoring and Interpretation' => array(
                        'Language tutoring',
                        'Language teaching',
                        'Language proficiency testing',
                        'Language learning materials',
                        'Language immersion programs',
                        'Language assessment',
                        'Interpretation services',
                        'Consecutive interpretation',
                        'Simultaneous interpretation',
                        'Whispered interpretation',
                        'Conference interpretation',
                        'Business interpretation',
                        'Legal interpretation',
                        'Medical interpretation',
                        'Community interpretation',
                        'Remote interpretation',
                        'Interpretation equipment',
                        'Language tutoring platforms',
                        'Language learning apps',
                        'Language interpretation software',
                    ),
                    'Translation and Localization Services' => array(
                        'Translation services',
                        'Document translation',
                        'Website localization',
                        'Software localization',
                        'Multilingual content creation',
                        'Certified translation',
                        'Technical translation',
                        'Legal translation',
                        'Medical translation',
                        'Business translation',
                        'Marketing translation',
                        'Localization testing',
                        'Quality assurance',
                        'Translation project management',
                        'Machine translation',
                        'Post-editing',
                        'Transcreation',
                        'Subtitling and captioning',
                        'Desktop publishing',
                        'Translation memory tools',
                    ),
                    'Blockchain, NFT and Cryptography' => array(
                        'Blockchain technology',
                        'Cryptocurrencies',
                        'Smart contracts',
                        'Decentralized finance (DeFi)',
                        'Blockchain development',
                        'Blockchain security',
                        'Tokenization',
                        'Non-fungible tokens (NFTs)',
                        'Digital art on blockchain',
                        'Cryptocurrency trading',
                        'Blockchain consensus mechanisms',
                        'Cryptocurrency mining',
                        'Blockchain scalability',
                        'Blockchain interoperability',
                        'Cryptography algorithms',
                        'Public-key cryptography',
                        'Digital signatures',
                        'Blockchain governance',
                        'Blockchain regulation',
                        'Blockchain consulting',
                    ),
                    'Desktop Application Development' => array(
                        'Desktop application design',
                        'User interface (UI) design',
                        'User experience (UX) design',
                        'Front-end development',
                        'Back-end development',
                        'Database integration',
                        'Cross-platform development',
                        'Software testing and debugging',
                        'Application security',
                        'Desktop application deployment',
                        'Maintenance and updates',
                        'Performance optimization',
                        'Version control',
                        'Error handling',
                        'Application documentation',
                        'Desktop application frameworks',
                        'Desktop application languages',
                        'Desktop application templates',
                        'Desktop application deployment tools',
                        'Desktop application licensing',
                    ),
                    'Ecommerce Development' => array(
                        'Ecommerce website design',
                        'Shopping cart integration',
                        'Payment gateway integration',
                        'Order management systems',
                        'Product catalog management',
                        'Inventory management',
                        'Shipping and logistics integration',
                        'Ecommerce analytics',
                        'Customer reviews and ratings',
                        'Secure online transactions',
                        'Mobile commerce (m-commerce)',
                        'Responsive web design',
                        'User account management',
                        'Ecommerce SEO',
                        'Ecommerce marketing',
                        'Ecommerce platform customization',
                        'Ecommerce platform migration',
                        'Ecommerce website maintenance',
                        'Ecommerce platform integration',
                        'Ecommerce performance optimization',
                    ),
                    'Game Design and Development' => array(
                        'Game concept development',
                        'Game mechanics',
                        'Game level design',
                        'Character design',
                        'Game prototyping',
                        'Game programming',
                        'Game art and animation',
                        'Game sound design',
                        'Gameplay testing',
                        'Game monetization',
                        'User interface (UI) design for games',
                        'Game engine development',
                        'Multiplayer game development',
                        'Virtual reality (VR) games',
                        'Augmented reality (AR) games',
                        'Mobile game development',
                        'Console game development',
                        'PC game development',
                        'Indie game development',
                        'Game design documentation',
                    ),
                    'Mobile Development' => array(
                        'iOS app development',
                        'Android app development',
                        'Cross-platform app development',
                        'Mobile UI/UX design',
                        'Mobile app testing',
                        'Mobile app optimization',
                        'Mobile app performance tuning',
                        'Push notifications',
                        'Mobile app security',
                        'Mobile app deployment',
                        'Mobile backend development',
                        'Hybrid app development',
                        'Mobile app prototyping',
                        'Mobile app maintenance',
                        'Mobile app analytics',
                        'AR (Augmented Reality) app development',
                        'VR (Virtual Reality) app development',
                        'Mobile app accessibility',
                        'Mobile app monetization',
                        'Mobile app marketing',
                    ),
                    'Product Management' => array(
                        'Product strategy',
                        'Product roadmap',
                        'Product requirements gathering',
                        'Market research and analysis',
                        'User research',
                        'Competitor analysis',
                        'Product design and wireframing',
                        'Agile product management',
                        'Scrum methodologies',
                        'Product backlog management',
                        'User stories and acceptance criteria',
                        'Product development process',
                        'Product launch planning',
                        'Product pricing and positioning',
                        'Product lifecycle management',
                        'Product performance tracking',
                        'Customer feedback and surveys',
                        'Product success metrics',
                        'Product management tools',
                        'Product management best practices',
                    ),
                    'QA Testing' => array(
                        'Test planning and strategy',
                        'Test case design',
                        'Functional testing',
                        'Regression testing',
                        'Performance testing',
                        'Load testing',
                        'Security testing',
                        'Usability testing',
                        'Accessibility testing',
                        'Compatibility testing',
                        'Cross-browser testing',
                        'Automation testing',
                        'Test script development',
                        'Defect tracking and management',
                        'Test data creation',
                        'Test environment setup',
                        'Test result analysis and reporting',
                        'Continuous integration and testing',
                        'Agile testing methodologies',
                        'QA testing tools',
                    ),
                    'Scripts and Utilities' => array(
                        'Scripting languages',
                        'Shell scripting',
                        'Automation scripts',
                        'Data processing scripts',
                        'Database scripts',
                        'Batch processing scripts',
                        'Data migration scripts',
                        'System administration scripts',
                        'Backup and restore scripts',
                        'Logging and monitoring scripts',
                        'File manipulation scripts',
                        'Network utility scripts',
                        'Error handling scripts',
                        'Deployment scripts',
                        'Scripting frameworks',
                        'Command-line utilities',
                        'Data parsing and extraction',
                        'Data transformation scripts',
                        'Scripting best practices',
                        'Scripting security considerations',
                    ),
                    'Web and Mobile Design' => array(
                        'UI/UX design',
                        'Responsive web design',
                        'Mobile-first design',
                        'Wireframing',
                        'Prototyping',
                        'Visual design',
                        'Typography',
                        'Color theory',
                        'Grid systems',
                        'Interaction design',
                        'Usability testing',
                        'User research',
                        'Information architecture',
                        'User personas',
                        'Design systems',
                        'Web and mobile branding',
                        'Illustration and icon design',
                        'Animation design',
                        'Mobile app design guidelines',
                        'Design tools and software',
                    ),
                    'Web Development' => array(
                        'HTML',
                        'CSS',
                        'JavaScript',
                        'Front-end development',
                        'Responsive web design',
                        'UI/UX development',
                        'Web frameworks',
                        'React',
                        'Angular',
                        'Vue',
                        'Laravel',
                        'Symfony',
                        'CodeIgniter',
                        'CakePHP',
                        'Zend Framework',
                        'Django',
                        'Flask',
                        'Ruby on Rails',
                        'Sinatra',
                        'Express.js',
                        'Meteor.js',
                        'Spring',
                        'ASP.NET',
                        'Ember.js',
                        'Backbone.js',
                        'Polymer',
                        'Sails.js',
                        'Back-end development',
                        'Server-side scripting',
                        'Database integration',
                        'API development and integration',
                        'Content management systems (CMS)',
                        'E-commerce development',
                        'Web security',
                        'Web performance optimization',
                        'Website maintenance and updates',
                        'Version control',
                        'Git',
                        'SEO best practices',
                        'Website accessibility',
                        'Web development tools',
                    ),
                    'Content Writing' => array(
                        'Blog writing',
                        'Article writing',
                        'Copywriting',
                        'SEO writing',
                        'Website content',
                        'Social media content',
                        'Press releases',
                        'Product descriptions',
                        'Email newsletters',
                        'Whitepapers',
                        'Case studies',
                        'E-book writing',
                        'Video scripts',
                        'Infographic content',
                        'Content editing',
                        'Content proofreading',
                        'Content strategy',
                        'Content marketing',
                        'Creative writing',
                        'Writing style guides',
                    ),
                    'Editing and Proofreading Services' => array(
                        'Copy editing',
                        'Proofreading',
                        'Line editing',
                        'Structural editing',
                        'Developmental editing',
                        'Substantive editing',
                        'Fact-checking',
                        'Grammar and punctuation editing',
                        'Consistency checking',
                        'Style guide adherence',
                        'Manuscript evaluation',
                        'Content editing',
                        'Publication editing',
                        'Citation and reference checking',
                        'Plagiarism checking',
                        'Editorial feedback and suggestions',
                        'Editing for clarity and conciseness',
                        'Editing for tone and style',
                        'Editing software and tools',
                        'Editing best practices',
                    ),
                    'Professional and Business Writing' => array(
                        'Business proposals',
                        'Business plans',
                        'Grant writing',
                        'Report writing',
                        'Whitepapers',
                        'Corporate communications',
                        'Company profiles',
                        'Policy and procedure manuals',
                        'Business correspondence',
                        'Employee handbooks',
                        'Executive summaries',
                        'Research papers',
                        'Speech writing',
                        'Marketing materials',
                        'Business presentations',
                        'Business writing style',
                        'Business writing etiquette',
                        'Professional document formatting',
                        'Business writing software',
                        'Business writing best practices',
                    ),
                    'Sales and Marketing Copywriting' => array(
                        'Sales emails',
                        'Sales letters',
                        'Sales landing pages',
                        'Sales scripts',
                        'Sales presentations',
                        'Sales collateral',
                        'Marketing copy',
                        'Ad copywriting',
                        'Taglines and slogans',
                        'Brochure copy',
                        'Product descriptions',
                        'Call-to-action (CTA) writing',
                        'Direct response copywriting',
                        'Social media copywriting',
                        'Email marketing copy',
                        'Sales and marketing storytelling',
                        'Sales and marketing strategy',
                        'Sales and marketing psychology',
                        'Sales and marketing analytics',
                        'Sales and marketing conversion optimization',
                    ),
                    'Programming' => array(
                        'Python',
                        'JavaScript',
                        'Java',
                        'C++',
                        'C#',
                        'Ruby',
                        'PHP',
                        'Swift',
                        'Go',
                        'Rust',
                        'TypeScript',
                        'Kotlin',
                        'Scala',
                        'Perl',
                        'HTML',
                        'CSS',
                        'SQL',
                        'Shell',
                        'MATLAB',
                        'R',
                        'Objective-C',
                        'Groovy',
                        'Lua',
                        'Haskell',
                        'Assembly',
                        'Lisp',
                        'Prolog',
                        'Cobol',
                        'Fortran',
                        'Pascal',
                        'Ada',
                        'Erlang',
                        'VB.NET',
                        'F#',
                        'Dart',
                        'Tcl',
                        'Julia',
                        'Crystal',
                        'PowerShell',
                    )
                ]
            ],
            'departments' => [
                'Human Resource', 'Customer Relationship', 'Finance', 'Checker'
            ],
            'attendance' => [
                'types' => [
                    'Regular',
                    'Late',
                    'Absent',
                    'No Time in',
                    'No Time out',
                    'Undertime',
                    'Overtime'
                ]
            ],
        ],
        'database' => [
            'local' => [
                'driver' => 'mysql',
                'host' => '127.0.0.1',
                'username' => 'root',
                'password' => '',
                'database' => 'expedite1',
            ],
            'production' => [
                'driver' => 'mysql',
                'host' => 'srv613.hstgr.io',
                'username' => 'u735446030_expedite_admin',
                'password' => 'expeditePH@2022',
                'database' => 'u735446030_expedite'
            ]
        ],
        'freelancer' => [
            'experience_levels' => ['Entry Level', 'Intermediate', 'Expert']
        ],
        'price' => [
            'ranges' => [
                '< 1000' => 'Less than PHP 1000',
                '1000-2000' => 'PHP 1000-PHP 2000',
                '2000-3000' => 'PHP 2000-PHP 3000',
                '3000-4000' => 'PHP 3000-4000',
                '4000-5000' => 'PHP 4000-PHP 5000',
                '> 5000' => 'More than 5000'
            ] 
        ],
        'languages' => [
            "Afrikaans",
            "Albanian",
            "Amharic",
            "Arabic",
            "Armenian",
            "Azerbaijani",
            "Basque",
            "Belarusian",
            "Bengali",
            "Bosnian",
            "Bulgarian",
            "Catalan",
            "Cebuano",
            "Chichewa",
            "Chinese",
            "Corsican",
            "Croatian",
            "Czech",
            "Danish",
            "Dutch",
            "English",
            "Esperanto",
            "Estonian",
            "Filipino",
            "Finnish",
            "French",
            "Frisian",
            "Galician",
            "Georgian",
            "German",
            "Greek",
            "Gujarati",
            "Haitian Creole",
            "Hausa",
            "Hawaiian",
            "Hebrew",
            "Hindi",
            "Hmong",
            "Hungarian",
            "Icelandic",
            "Igbo",
            "Indonesian",
            "Irish",
            "Italian",
            "Japanese",
            "Javanese",
            "Kannada",
            "Kazakh",
            "Khmer",
            "Kinyarwanda",
            "Korean",
            "Kurdish",
            "Kyrgyz",
            "Lao",
            "Latin",
            "Latvian",
            "Lithuanian",
            "Luxembourgish",
            "Macedonian",
            "Malagasy",
            "Malay",
            "Malayalam",
            "Maltese",
            "Maori",
            "Marathi",
            "Mongolian",
            "Myanmar (Burmese)",
            "Nepali",
            "Norwegian",
            "Odia (Oriya)",
            "Pashto",
            "Persian",
            "Polish",
            "Portuguese",
            "Punjabi",
            "Romanian",
            "Russian",
            "Samoan",
            "Scots Gaelic",
            "Serbian",
            "Sesotho",
            "Shona",
            "Sindhi",
            "Sinhala",
            "Slovak",
            "Slovenian",
            "Somali",
            "Spanish",
            "Sundanese",
            "Swahili",
            "Swedish",
            "Tajik",
            "Tamil",
            "Tatar",
            "Telugu",
            "Thai",
            "Turkish",
            "Turkmen",
            "Ukrainian",
            "Urdu",
            "Uyghur",
            "Uzbek",
            "Vietnamese",
            "Welsh",
            "Xhosa",
            "Yiddish",
            "Yoruba",
            "Zulu"
        ]
    ];

	if(isset($_CONFIG)) {
		function config($k) {
			global $_CONFIG;
			$keys = explode('.', $k);

			$arr = $_CONFIG;
			foreach ($keys as $key) {
				if (isset($arr[$key])) {
					$arr = $arr[$key];
				} else {
					return '';
				}
			}
			return $arr;
		}
	}
?>